### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by nobody5050** [HourGlss/HourCrypto#2]
How would I put this into practice? With simplecoin it was easy for there was only 2 python files however here I have no idea where even to start

**Comment by HourGlss** [comment]
Documentation will be created once project is functional as a whole. Currently, each of the "problems" with simplecoin are being addressed one at a time.
Simplecoin wallet creation is broken
Simplecoin does not utilize proper blockchain structure, a list is NOT enough
Simplecoin did not actually have working networking for block sharing
Simplecoin ran out of memory due to bad practice of sharing information between processes and not storing large amounts of non-necessary data in RAM instead of on disk
Simplecoin does not function as a currency because transactions are not logically evaluated
Simplecoin has no method of block validation
Simplecoin does not require transaction validation from non-origin nodes.

If you want more detail on any of those, please communicate with me directly, I don't want to cause drama with the creators of SimpleCoin. I really appreciate the work they have done, their project just has too many major issues for a "fix" to be developed. Discord: Xyf#1337

**Comment by HourGlss** [comment]
https://trello.com/b/PZSadgSB/hourcrypto

**Comment by nobody5050** [comment]
Sounds good

**Comment by nobody5050** [comment]
I’ve been looking at your git history and I see you really have improved the original code of simple crypto

**Comment by nobody5050** [comment]
I’ve been looking at your git history and I see you really have improved the original code of simple crypto
